# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ruhtra/projets/E4_POO3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ruhtra/projets/E4_POO3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruhtra/projets/E4_POO3/CMakeFiles /home/ruhtra/projets/E4_POO3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruhtra/projets/E4_POO3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named exo1

# Build rule for target.
exo1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exo1
.PHONY : exo1

# fast build rule for target.
exo1/fast:
	$(MAKE) -f CMakeFiles/exo1.dir/build.make CMakeFiles/exo1.dir/build
.PHONY : exo1/fast

#=============================================================================
# Target rules for targets named exo2

# Build rule for target.
exo2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exo2
.PHONY : exo2

# fast build rule for target.
exo2/fast:
	$(MAKE) -f CMakeFiles/exo2.dir/build.make CMakeFiles/exo2.dir/build
.PHONY : exo2/fast

#=============================================================================
# Target rules for targets named exo3

# Build rule for target.
exo3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exo3
.PHONY : exo3

# fast build rule for target.
exo3/fast:
	$(MAKE) -f CMakeFiles/exo3.dir/build.make CMakeFiles/exo3.dir/build
.PHONY : exo3/fast

#=============================================================================
# Target rules for targets named exo4

# Build rule for target.
exo4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exo4
.PHONY : exo4

# fast build rule for target.
exo4/fast:
	$(MAKE) -f CMakeFiles/exo4.dir/build.make CMakeFiles/exo4.dir/build
.PHONY : exo4/fast

src/cls/exo4.o: src/cls/exo4.cpp.o

.PHONY : src/cls/exo4.o

# target to build an object file
src/cls/exo4.cpp.o:
	$(MAKE) -f CMakeFiles/exo4.dir/build.make CMakeFiles/exo4.dir/src/cls/exo4.cpp.o
.PHONY : src/cls/exo4.cpp.o

src/cls/exo4.i: src/cls/exo4.cpp.i

.PHONY : src/cls/exo4.i

# target to preprocess a source file
src/cls/exo4.cpp.i:
	$(MAKE) -f CMakeFiles/exo4.dir/build.make CMakeFiles/exo4.dir/src/cls/exo4.cpp.i
.PHONY : src/cls/exo4.cpp.i

src/cls/exo4.s: src/cls/exo4.cpp.s

.PHONY : src/cls/exo4.s

# target to generate assembly for a file
src/cls/exo4.cpp.s:
	$(MAKE) -f CMakeFiles/exo4.dir/build.make CMakeFiles/exo4.dir/src/cls/exo4.cpp.s
.PHONY : src/cls/exo4.cpp.s

src/io/exo1.o: src/io/exo1.cpp.o

.PHONY : src/io/exo1.o

# target to build an object file
src/io/exo1.cpp.o:
	$(MAKE) -f CMakeFiles/exo1.dir/build.make CMakeFiles/exo1.dir/src/io/exo1.cpp.o
.PHONY : src/io/exo1.cpp.o

src/io/exo1.i: src/io/exo1.cpp.i

.PHONY : src/io/exo1.i

# target to preprocess a source file
src/io/exo1.cpp.i:
	$(MAKE) -f CMakeFiles/exo1.dir/build.make CMakeFiles/exo1.dir/src/io/exo1.cpp.i
.PHONY : src/io/exo1.cpp.i

src/io/exo1.s: src/io/exo1.cpp.s

.PHONY : src/io/exo1.s

# target to generate assembly for a file
src/io/exo1.cpp.s:
	$(MAKE) -f CMakeFiles/exo1.dir/build.make CMakeFiles/exo1.dir/src/io/exo1.cpp.s
.PHONY : src/io/exo1.cpp.s

src/io/exo2.o: src/io/exo2.cpp.o

.PHONY : src/io/exo2.o

# target to build an object file
src/io/exo2.cpp.o:
	$(MAKE) -f CMakeFiles/exo2.dir/build.make CMakeFiles/exo2.dir/src/io/exo2.cpp.o
.PHONY : src/io/exo2.cpp.o

src/io/exo2.i: src/io/exo2.cpp.i

.PHONY : src/io/exo2.i

# target to preprocess a source file
src/io/exo2.cpp.i:
	$(MAKE) -f CMakeFiles/exo2.dir/build.make CMakeFiles/exo2.dir/src/io/exo2.cpp.i
.PHONY : src/io/exo2.cpp.i

src/io/exo2.s: src/io/exo2.cpp.s

.PHONY : src/io/exo2.s

# target to generate assembly for a file
src/io/exo2.cpp.s:
	$(MAKE) -f CMakeFiles/exo2.dir/build.make CMakeFiles/exo2.dir/src/io/exo2.cpp.s
.PHONY : src/io/exo2.cpp.s

src/ref/exo1.o: src/ref/exo1.cpp.o

.PHONY : src/ref/exo1.o

# target to build an object file
src/ref/exo1.cpp.o:
	$(MAKE) -f CMakeFiles/exo3.dir/build.make CMakeFiles/exo3.dir/src/ref/exo1.cpp.o
.PHONY : src/ref/exo1.cpp.o

src/ref/exo1.i: src/ref/exo1.cpp.i

.PHONY : src/ref/exo1.i

# target to preprocess a source file
src/ref/exo1.cpp.i:
	$(MAKE) -f CMakeFiles/exo3.dir/build.make CMakeFiles/exo3.dir/src/ref/exo1.cpp.i
.PHONY : src/ref/exo1.cpp.i

src/ref/exo1.s: src/ref/exo1.cpp.s

.PHONY : src/ref/exo1.s

# target to generate assembly for a file
src/ref/exo1.cpp.s:
	$(MAKE) -f CMakeFiles/exo3.dir/build.make CMakeFiles/exo3.dir/src/ref/exo1.cpp.s
.PHONY : src/ref/exo1.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... exo1"
	@echo "... exo2"
	@echo "... exo3"
	@echo "... exo4"
	@echo "... src/cls/exo4.o"
	@echo "... src/cls/exo4.i"
	@echo "... src/cls/exo4.s"
	@echo "... src/io/exo1.o"
	@echo "... src/io/exo1.i"
	@echo "... src/io/exo1.s"
	@echo "... src/io/exo2.o"
	@echo "... src/io/exo2.i"
	@echo "... src/io/exo2.s"
	@echo "... src/ref/exo1.o"
	@echo "... src/ref/exo1.i"
	@echo "... src/ref/exo1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

